local c = require("zed_onedark.colors").colors

local M = {}

local function hl(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

local function link(group, target)
    hl(group, { link = target })
end

local function merge_highlight(group, opts)
    if opts.link ~= nil then
        return opts
    end

    local ok, current = pcall(vim.api.nvim_get_hl, 0, { name = group, link = false })
    if not ok then
        current = {}
    end

    return vim.tbl_deep_extend("force", current, opts)
end

local function apply_overrides(overrides)
    for group, opts in pairs(overrides or {}) do
        hl(group, merge_highlight(group, opts))
    end
end

function M.setup(config)
    config = config or {}

    vim.o.termguicolors = true
    vim.o.background = "dark"

    vim.cmd("highlight clear")
    if vim.fn.exists("syntax_on") == 1 then
        vim.cmd("syntax reset")
    end

    vim.g.colors_name = "zed_onedark"

    hl("Normal", { fg = c.fg, bg = c.bg })
    hl("NormalNC", { fg = c.fg, bg = c.bg })
    hl("SignColumn", { fg = c.fg, bg = c.bg })
    hl("EndOfBuffer", { fg = c.bg, bg = c.bg })
    hl("CursorLine", { bg = c.bg_subtle })
    hl("CursorColumn", { bg = c.bg_subtle })
    hl("ColorColumn", { bg = c.bg_subtle })
    hl("CursorLineNr", { fg = c.line_nr_active, bg = c.bg, bold = false })
    hl("LineNr", { fg = c.line_nr, bg = c.bg })
    hl("VertSplit", { fg = c.border, bg = c.bg })
    hl("WinSeparator", { fg = c.border, bg = c.bg })
    hl("Folded", { fg = c.fg_muted, bg = c.bg_subtle })
    hl("FoldColumn", { fg = c.line_nr, bg = c.bg })
    hl("MatchParen", { fg = c.fg_bright, bg = c.bg_hover, bold = false })
    hl("Visual", { bg = c.visual })
    hl("VisualNOS", { bg = c.visual })
    hl("Search", { fg = c.fg_bright, bg = c.search })
    hl("CurSearch", { fg = c.fg_bright, bg = c.search_current })
    hl("IncSearch", { fg = c.fg_bright, bg = c.search_current })
    hl("Substitute", { fg = c.fg_bright, bg = c.search_current })
    hl("Directory", { fg = c.blue })
    hl("Title", { fg = c.red, bold = false })
    hl("ErrorMsg", { fg = c.error })
    hl("WarningMsg", { fg = c.warning })
    hl("MoreMsg", { fg = c.info })
    hl("Question", { fg = c.info })
    hl("ModeMsg", { fg = c.fg_bright })
    hl("Conceal", { fg = c.line_nr })
    hl("NonText", { fg = c.line_nr })
    hl("SpecialKey", { fg = c.line_nr })
    hl("Whitespace", { fg = c.line_nr })
    hl("WinBar", { fg = c.fg_muted, bg = c.bg_subtle })
    hl("WinBarNC", { fg = c.fg_placeholder, bg = c.bg_element })
    hl("NormalFloat", { fg = c.fg, bg = c.float })
    hl("FloatBorder", { fg = c.border, bg = c.float })
    hl("FloatTitle", { fg = c.accent, bg = c.float })
    hl("Pmenu", { fg = c.fg, bg = c.pmenu })
    hl("PmenuSel", { fg = c.fg_bright, bg = c.pmenu_sel })
    hl("PmenuSbar", { bg = c.bg_hover })
    hl("PmenuThumb", { bg = c.fg_muted })
    hl("StatusLine", { fg = c.fg, bg = c.bg_alt })
    hl("StatusLineNC", { fg = c.fg_placeholder, bg = c.bg_element })
    hl("TabLine", { fg = c.fg_muted, bg = c.bg_subtle })
    hl("TabLineFill", { fg = c.fg_muted, bg = c.bg_subtle })
    hl("TabLineSel", { fg = c.fg_bright, bg = c.bg })
    hl("WildMenu", { fg = c.fg_bright, bg = c.bg_active })

    hl("DiffAdd", { fg = c.green, bg = c.diff_add_bg })
    hl("DiffChange", { fg = c.yellow, bg = c.diff_change_bg })
    hl("DiffDelete", { fg = c.red, bg = c.diff_delete_bg })
    hl("DiffText", { fg = c.fg_bright, bg = c.bg_hover })

    hl("DiagnosticError", { fg = c.error })
    hl("DiagnosticWarn", { fg = c.warning })
    hl("DiagnosticInfo", { fg = c.info })
    hl("DiagnosticHint", { fg = c.hint })
    hl("DiagnosticOk", { fg = c.success })
    hl("DiagnosticVirtualTextError", { fg = c.error, bg = c.error_bg })
    hl("DiagnosticVirtualTextWarn", { fg = c.warning, bg = c.warning_bg })
    hl("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.info_bg })
    hl("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.hint_bg })
    hl("DiagnosticVirtualTextOk", { fg = c.success, bg = c.success_bg })
    hl("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
    hl("DiagnosticUnderlineWarn", { sp = c.warning, undercurl = true })
    hl("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
    hl("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
    hl("DiagnosticUnderlineOk", { sp = c.success, undercurl = true })
    hl("DiagnosticSignError", { fg = c.error, bg = c.bg })
    hl("DiagnosticSignWarn", { fg = c.warning, bg = c.bg })
    hl("DiagnosticSignInfo", { fg = c.info, bg = c.bg })
    hl("DiagnosticSignHint", { fg = c.hint, bg = c.bg })
    hl("DiagnosticSignOk", { fg = c.success, bg = c.bg })

    hl("Comment", { fg = c.comment })
    hl("Constant", { fg = "#dfc184" })
    hl("String", { fg = c.green })
    hl("Character", { fg = c.green })
    hl("Number", { fg = c.orange })
    hl("Boolean", { fg = c.orange })
    hl("Float", { fg = c.orange })
    hl("Identifier", { fg = c.fg })
    hl("Function", { fg = c.blue })
    hl("Statement", { fg = c.purple })
    hl("Conditional", { fg = c.purple })
    hl("Repeat", { fg = c.purple })
    hl("Label", { fg = c.accent })
    hl("Operator", { fg = c.cyan })
    hl("Keyword", { fg = c.purple })
    hl("Exception", { fg = c.purple })
    hl("PreProc", { fg = c.fg_bright })
    hl("Include", { fg = c.purple })
    hl("Define", { fg = c.purple })
    hl("Macro", { fg = c.fg_bright })
    hl("PreCondit", { fg = c.purple })
    hl("Type", { fg = c.cyan })
    hl("StorageClass", { fg = c.purple })
    hl("Structure", { fg = c.cyan })
    hl("Typedef", { fg = c.cyan })
    hl("Special", { fg = c.orange })
    hl("SpecialComment", { fg = c.comment_doc })
    hl("Underlined", { fg = c.blue, underline = true })
    hl("Todo", { fg = c.accent, bg = c.bg_subtle, bold = false })

    link("@comment", "Comment")
    hl("@comment.documentation", { fg = c.comment_doc })
    hl("@attribute", { fg = c.accent })
    hl("@boolean", { fg = c.orange })
    hl("@constant", { fg = "#dfc184" })
    hl("@constant.builtin", { fg = "#dfc184" })
    hl("@constant.macro", { fg = c.fg_bright })
    hl("@constructor", { fg = c.blue })
    hl("@function", { fg = c.blue })
    hl("@function.builtin", { fg = c.blue })
    hl("@function.call", { fg = c.blue })
    hl("@function.method", { fg = c.blue })
    hl("@function.method.call", { fg = c.blue })
    hl("@keyword", { fg = c.purple })
    hl("@keyword.conditional", { fg = c.purple })
    hl("@keyword.function", { fg = c.purple })
    hl("@keyword.operator", { fg = c.purple })
    hl("@keyword.repeat", { fg = c.purple })
    hl("@keyword.return", { fg = c.purple })
    hl("@label", { fg = c.accent })
    hl("@module", { fg = c.fg_bright })
    hl("@namespace", { fg = c.fg_bright })
    hl("@number", { fg = c.orange })
    hl("@operator", { fg = c.cyan })
    hl("@parameter", { fg = c.fg })
    hl("@parameter.reference", { fg = c.fg })
    hl("@property", { fg = c.red })
    hl("@field", { fg = c.red })
    hl("@punctuation", { fg = c.fg })
    hl("@punctuation.bracket", { fg = "#b2b9c6" })
    hl("@punctuation.delimiter", { fg = "#b2b9c6" })
    hl("@punctuation.special", { fg = "#b1574b" })
    hl("@string", { fg = c.green })
    hl("@string.escape", { fg = c.comment_doc })
    hl("@string.regex", { fg = c.orange })
    hl("@string.special", { fg = c.orange })
    hl("@string.special.symbol", { fg = c.orange })
    hl("@tag", { fg = c.accent })
    hl("@text.literal", { fg = c.green })
    hl("@type", { fg = c.cyan })
    hl("@type.builtin", { fg = c.cyan })
    hl("@type.definition", { fg = c.cyan })
    hl("@variable", { fg = c.fg })
    hl("@variable.builtin", { fg = c.orange })
    hl("@variable.member", { fg = c.red })
    hl("@variable.parameter", { fg = c.fg })
    hl("@markup.link", { fg = c.blue, underline = true })
    hl("@markup.link.label", { fg = c.blue })
    hl("@markup.link.url", { fg = c.cyan, underline = true })
    hl("@markup.list", { fg = c.red })
    hl("@markup.heading", { fg = c.red })
    hl("@markup.raw", { fg = c.green })
    hl("@markup.raw.block", { fg = c.green, bg = c.bg_subtle })

    link("TSAttribute", "@attribute")
    link("TSBoolean", "@boolean")
    link("TSComment", "@comment")
    link("TSConstBuiltin", "@constant.builtin")
    link("TSConstant", "@constant")
    link("TSConstructor", "@constructor")
    link("TSField", "@field")
    link("TSFunction", "@function")
    link("TSFuncBuiltin", "@function.builtin")
    link("TSKeyword", "@keyword")
    link("TSMethod", "@function.method")
    link("TSNumber", "@number")
    link("TSOperator", "@operator")
    link("TSProperty", "@property")
    link("TSPunctBracket", "@punctuation.bracket")
    link("TSPunctDelimiter", "@punctuation.delimiter")
    link("TSString", "@string")
    link("TSStringEscape", "@string.escape")
    link("TSTag", "@tag")
    link("TSType", "@type")
    link("TSVariable", "@variable")
    link("TSVariableBuiltin", "@variable.builtin")

    hl("@lsp.type.class", { fg = c.cyan })
    hl("@lsp.type.comment", { fg = c.comment })
    hl("@lsp.type.decorator", { fg = c.accent })
    hl("@lsp.type.enum", { fg = c.cyan })
    hl("@lsp.type.enumMember", { fg = c.orange })
    hl("@lsp.type.function", { fg = c.blue })
    hl("@lsp.type.interface", { fg = c.cyan })
    hl("@lsp.type.keyword", { fg = c.purple })
    hl("@lsp.type.macro", { fg = c.fg_bright })
    hl("@lsp.type.method", { fg = c.blue })
    hl("@lsp.type.modifier", { fg = c.purple })
    hl("@lsp.type.namespace", { fg = c.fg_bright })
    hl("@lsp.type.number", { fg = c.orange })
    hl("@lsp.type.operator", { fg = c.cyan })
    hl("@lsp.type.parameter", { fg = c.fg })
    hl("@lsp.type.property", { fg = c.red })
    hl("@lsp.type.regexp", { fg = c.orange })
    hl("@lsp.type.string", { fg = c.green })
    hl("@lsp.type.struct", { fg = c.cyan })
    hl("@lsp.type.type", { fg = c.cyan })
    hl("@lsp.type.typeParameter", { fg = c.cyan })
    hl("@lsp.type.variable", { fg = c.fg })
    hl("@lsp.type.field", { fg = c.red })
    hl("@lsp.mod.declaration", {})
    hl("@lsp.mod.definition", {})
    hl("@lsp.mod.readonly", {})
    hl("@lsp.mod.defaultLibrary", { fg = c.orange })

    hl("SpellBad", { sp = c.error, undercurl = true })
    hl("SpellCap", { sp = c.info, undercurl = true })
    hl("SpellRare", { sp = c.purple, undercurl = true })
    hl("SpellLocal", { sp = c.cyan_bright, undercurl = true })

    hl("TelescopeNormal", { fg = c.fg, bg = c.bg_subtle })
    hl("TelescopeBorder", { fg = c.border, bg = c.bg_subtle })
    hl("TelescopeTitle", { fg = c.accent, bg = c.bg_subtle })
    hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg_hover })
    hl("TelescopePromptBorder", { fg = c.border_focus, bg = c.bg_hover })
    hl("TelescopePromptTitle", { fg = c.accent, bg = c.bg_hover })
    hl("TelescopePromptPrefix", { fg = c.accent, bg = c.bg_hover })
    hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg_subtle })
    hl("TelescopePreviewBorder", { fg = c.border, bg = c.bg_subtle })
    hl("TelescopeResultsNormal", { fg = c.fg, bg = c.bg_subtle })
    hl("TelescopeResultsBorder", { fg = c.border, bg = c.bg_subtle })
    hl("TelescopeSelection", { fg = c.fg_bright, bg = c.bg_active })
    hl("TelescopeSelectionCaret", { fg = c.accent, bg = c.bg_active })
    hl("TelescopeMatching", { fg = c.accent, bold = false })

    hl("CmpDocumentation", { fg = c.fg, bg = c.bg_subtle })
    hl("CmpDocumentationBorder", { fg = c.border, bg = c.bg_subtle })
    hl("CmpItemAbbr", { fg = c.fg })
    hl("CmpItemAbbrDeprecated", { fg = c.fg_placeholder, strikethrough = true })
    hl("CmpItemAbbrMatch", { fg = c.accent, bold = false })
    hl("CmpItemAbbrMatchFuzzy", { fg = c.accent })
    hl("CmpItemMenu", { fg = c.fg_muted })
    hl("CmpItemKindText", { fg = c.fg })
    hl("CmpItemKindVariable", { fg = c.fg })
    hl("CmpItemKindFunction", { fg = c.blue })
    hl("CmpItemKindMethod", { fg = c.blue })
    hl("CmpItemKindKeyword", { fg = c.purple })
    hl("CmpItemKindProperty", { fg = c.red })
    hl("CmpItemKindField", { fg = c.red })
    hl("CmpItemKindClass", { fg = c.cyan })
    hl("CmpItemKindInterface", { fg = c.cyan })
    hl("CmpItemKindModule", { fg = c.fg_bright })
    hl("CmpItemKindStruct", { fg = c.cyan })
    hl("CmpItemKindSnippet", { fg = c.green })
    hl("CmpItemKindFile", { fg = c.fg_muted })

    hl("GitSignsAdd", { fg = c.diff_add, bg = c.bg })
    hl("GitSignsChange", { fg = c.diff_change, bg = c.bg })
    hl("GitSignsDelete", { fg = c.diff_delete, bg = c.bg })
    hl("GitSignsCurrentLineBlame", { fg = c.predictive, italic = true })

    hl("WhichKey", { fg = c.accent })
    hl("WhichKeyGroup", { fg = c.purple })
    hl("WhichKeyDesc", { fg = c.fg })
    hl("WhichKeySeparator", { fg = c.comment })
    hl("WhichKeyFloat", { bg = c.bg_subtle })
    hl("WhichKeyBorder", { fg = c.border, bg = c.bg_subtle })
    hl("WhichKeyValue", { fg = c.fg_placeholder })

    hl("NeoTreeNormal", { fg = c.fg, bg = c.bg_subtle })
    hl("NeoTreeNormalNC", { fg = c.fg, bg = c.bg_subtle })
    hl("NeoTreeEndOfBuffer", { fg = c.bg_subtle, bg = c.bg_subtle })
    hl("NeoTreeWinSeparator", { fg = c.border, bg = c.bg_subtle })
    hl("NeoTreeBorder", { fg = c.border, bg = c.bg_subtle })
    hl("NeoTreeTitleBar", { fg = c.fg_bright, bg = c.bg_hover })
    hl("NeoTreeFileName", { fg = c.fg })
    hl("NeoTreeMessage", { fg = c.fg_muted })
    hl("NeoTreeFileNameOpened", { fg = c.fg_bright })
    hl("NeoTreeDirectoryName", { fg = c.blue })
    hl("NeoTreeDirectoryIcon", { fg = c.blue })
    hl("NeoTreeIndentMarker", { fg = c.border_variant })
    hl("NeoTreeRootName", { fg = c.accent, bold = false })
    hl("NeoTreeGitAdded", { fg = c.diff_add })
    hl("NeoTreeGitDeleted", { fg = c.diff_delete })
    hl("NeoTreeGitModified", { fg = c.diff_change })
    hl("NeoTreeGitConflict", { fg = c.warning })
    hl("NeoTreeFloatBorder", { fg = c.border, bg = c.bg_subtle })
    hl("NeoTreeFloatTitle", { fg = c.accent, bg = c.bg_subtle })
    hl("NeoTreeCursorLine", { bg = c.bg_active })

    hl("SnacksNormal", { fg = c.fg, bg = c.bg_subtle })
    hl("SnacksBorder", { fg = c.border, bg = c.bg_subtle })
    hl("SnacksTitle", { fg = c.accent, bg = c.bg_subtle })
    hl("SnacksInputNormal", { fg = c.fg, bg = c.bg_hover })
    hl("SnacksInputBorder", { fg = c.border_focus, bg = c.bg_hover })

    hl("NoiceCmdlinePopup", { fg = c.fg, bg = c.bg_subtle })
    hl("NoiceCmdlinePopupBorder", { fg = c.border_focus, bg = c.bg_subtle })
    hl("NoiceConfirm", { fg = c.fg, bg = c.bg_subtle })
    hl("NoiceConfirmBorder", { fg = c.border, bg = c.bg_subtle })
    hl("NoicePopup", { fg = c.fg, bg = c.bg_subtle })
    hl("NoicePopupBorder", { fg = c.border, bg = c.bg_subtle })
    hl("NoiceMini", { fg = c.fg, bg = c.bg_subtle })
    hl("NoiceFormatTitle", { fg = c.accent })
    hl("NoiceFormatProgressDone", { fg = c.accent })
    hl("NoiceFormatProgressTodo", { fg = c.border })

    hl("LazyNormal", { fg = c.fg, bg = c.bg_subtle })
    hl("LazyBorder", { fg = c.border, bg = c.bg_subtle })
    hl("LazyButton", { fg = c.fg, bg = c.bg_hover })
    hl("LazyButtonActive", { fg = c.fg_bright, bg = c.bg_active })
    hl("LazyH1", { fg = c.bg, bg = c.accent })
    hl("LazySpecial", { fg = c.accent })
    hl("LazyReasonPlugin", { fg = c.purple })
    hl("LazyReasonEvent", { fg = c.yellow })
    hl("LazyReasonStart", { fg = c.info })
    hl("LazyReasonRuntime", { fg = c.green })
    hl("LazyReasonRequire", { fg = c.orange })
    hl("LazyProgressDone", { fg = c.accent })
    hl("LazyProgressTodo", { fg = c.border })

    hl("RenderMarkdownH1", { fg = c.red, bold = false })
    hl("RenderMarkdownH2", { fg = c.yellow, bold = false })
    hl("RenderMarkdownH3", { fg = c.green, bold = false })
    hl("RenderMarkdownH4", { fg = c.cyan, bold = false })
    hl("RenderMarkdownCode", { bg = c.bg_subtle })
    hl("RenderMarkdownBullet", { fg = c.red })
    hl("RenderMarkdownQuote", { fg = c.comment_doc })
    hl("RenderMarkdownLink", { fg = c.blue, underline = true })

    apply_overrides(config.highlights)
end

return M
